// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Crypto int32

const (
	Crypto_SECP Crypto = 0
	Crypto_SM2  Crypto = 1
)

var Crypto_name = map[int32]string{
	0: "SECP",
	1: "SM2",
}
var Crypto_value = map[string]int32{
	"SECP": 0,
	"SM2":  1,
}

func (x Crypto) String() string {
	return proto.EnumName(Crypto_name, int32(x))
}
func (Crypto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_transaction_db31f5f4782af531, []int{0}
}

type Transaction struct {
	To                   string   `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`
	Quota                uint64   `protobuf:"varint,3,opt,name=quota" json:"quota,omitempty"`
	ValidUntilBlock      uint64   `protobuf:"varint,4,opt,name=valid_until_block,json=validUntilBlock" json:"valid_until_block,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Value                uint64   `protobuf:"varint,6,opt,name=value" json:"value,omitempty"`
	ChainId              uint32   `protobuf:"varint,7,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Version              uint32   `protobuf:"varint,8,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_db31f5f4782af531, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Transaction) GetQuota() uint64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *Transaction) GetValidUntilBlock() uint64 {
	if m != nil {
		return m.ValidUntilBlock
	}
	return 0
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type UnverifiedTransaction struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	Signature            []byte       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Crypto               Crypto       `protobuf:"varint,3,opt,name=crypto,enum=proto.Crypto" json:"crypto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UnverifiedTransaction) Reset()         { *m = UnverifiedTransaction{} }
func (m *UnverifiedTransaction) String() string { return proto.CompactTextString(m) }
func (*UnverifiedTransaction) ProtoMessage()    {}
func (*UnverifiedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_db31f5f4782af531, []int{1}
}
func (m *UnverifiedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnverifiedTransaction.Unmarshal(m, b)
}
func (m *UnverifiedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnverifiedTransaction.Marshal(b, m, deterministic)
}
func (dst *UnverifiedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnverifiedTransaction.Merge(dst, src)
}
func (m *UnverifiedTransaction) XXX_Size() int {
	return xxx_messageInfo_UnverifiedTransaction.Size(m)
}
func (m *UnverifiedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_UnverifiedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_UnverifiedTransaction proto.InternalMessageInfo

func (m *UnverifiedTransaction) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *UnverifiedTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *UnverifiedTransaction) GetCrypto() Crypto {
	if m != nil {
		return m.Crypto
	}
	return Crypto_SECP
}

func init() {
	proto.RegisterType((*Transaction)(nil), "proto.Transaction")
	proto.RegisterType((*UnverifiedTransaction)(nil), "proto.UnverifiedTransaction")
	proto.RegisterEnum("proto.Crypto", Crypto_name, Crypto_value)
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_db31f5f4782af531) }

var fileDescriptor_transaction_db31f5f4782af531 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0xff, 0x69, 0xd3, 0x24, 0xbd, 0x69, 0xfb, 0xb7, 0x17, 0x85, 0x11, 0x5d, 0x84, 0x82,
	0x10, 0xba, 0xe8, 0x22, 0xfa, 0x04, 0x16, 0x17, 0x2e, 0x04, 0x99, 0xda, 0x75, 0x98, 0x26, 0x51,
	0x07, 0xc3, 0x4c, 0x9d, 0x4c, 0x02, 0xbe, 0x86, 0xcf, 0xe6, 0x03, 0x49, 0x66, 0x02, 0xcd, 0x2a,
	0x39, 0xdf, 0x39, 0x73, 0xe0, 0x1e, 0x58, 0x19, 0xcd, 0x65, 0xcd, 0x73, 0x23, 0x94, 0xdc, 0x9e,
	0xb4, 0x32, 0x0a, 0x27, 0xf6, 0xb3, 0xfe, 0x25, 0x10, 0xbd, 0x9e, 0x4d, 0x5c, 0xc0, 0xc8, 0x28,
	0x4a, 0x62, 0x92, 0x4c, 0xd9, 0xc8, 0x28, 0xbc, 0x80, 0x89, 0x54, 0x32, 0x2f, 0xe9, 0xc8, 0x22,
	0x27, 0x3a, 0xfa, 0xd5, 0x28, 0xc3, 0xe9, 0x38, 0x26, 0x89, 0xc7, 0x9c, 0xc0, 0x0d, 0xac, 0x5a,
	0x5e, 0x89, 0x22, 0x6b, 0xa4, 0x11, 0x55, 0x76, 0xac, 0x54, 0xfe, 0x49, 0x3d, 0x9b, 0xf8, 0x6f,
	0x8d, 0x43, 0xc7, 0x1f, 0x3a, 0x8c, 0x08, 0x5e, 0xc1, 0x0d, 0xa7, 0x93, 0x98, 0x24, 0x33, 0x66,
	0xff, 0xbb, 0xd6, 0x96, 0x57, 0x4d, 0x49, 0x7d, 0xd7, 0x6a, 0x05, 0x5e, 0x41, 0x98, 0x7f, 0x70,
	0x21, 0x33, 0x51, 0xd0, 0x20, 0x26, 0xc9, 0x9c, 0x05, 0x56, 0x3f, 0x15, 0x48, 0x21, 0x68, 0x4b,
	0x5d, 0x0b, 0x25, 0x69, 0xe8, 0x9c, 0x5e, 0xae, 0x7f, 0x08, 0x5c, 0x1e, 0x64, 0x5b, 0x6a, 0xf1,
	0x26, 0xca, 0x62, 0x78, 0xe0, 0x3d, 0x44, 0x83, 0x31, 0xec, 0xa5, 0x51, 0x8a, 0x6e, 0x94, 0xed,
	0x20, 0xc8, 0x86, 0x31, 0xbc, 0x81, 0x69, 0x2d, 0xde, 0x25, 0x37, 0x8d, 0x76, 0x53, 0xcc, 0xd8,
	0x19, 0xe0, 0x2d, 0xf8, 0xb9, 0xfe, 0x3e, 0x19, 0x65, 0xf7, 0x58, 0xa4, 0xf3, 0xbe, 0x6e, 0x67,
	0x21, 0xeb, 0xcd, 0xcd, 0x35, 0xf8, 0x8e, 0x60, 0x08, 0xde, 0xfe, 0x71, 0xf7, 0xb2, 0xfc, 0x87,
	0x01, 0x8c, 0xf7, 0xcf, 0xe9, 0x92, 0x1c, 0x7d, 0xfb, 0xe4, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0x7f, 0x7a, 0xf9, 0xab, 0x01, 0x00, 0x00,
}
